// Generated by CoffeeScript 1.8.0
(function() {
  var data;

  data = [];

  $.get('/fu/data.json', function(dataIn) {
    data = dataIn;
    return console.log(dataIn);
  });

  ($('BUTTON#submitButton')).click(function() {
    var item, list, number, out;
    number = Number(($('INPUT#inputField')).val());
    list = [number];
    out = [];
    while (item = list.shift()) {
      if (data[item]) {
        list.push.apply(list, data[item]);
      }
      if (data[item]) {
        out.push.apply(out, data[item]);
      }
    }
    out.sort(function(a, b) {
      return Number(a) - Number(b);
    });
    return console.log(out);
  });

}).call(this);
