// Generated by CoffeeScript 1.8.0
(function() {
  var data;

  data = [];

  $.get('/fu/data.json', function(dataIn) {
    return data = dataIn;
  });

  ($(document)).ready(function() {
    ($('BUTTON#submitButton')).click(function() {
      var item, list, number, out, t, txt, _i, _len;
      console.log('clicked');
      number = Number(($('INPUT#inputField')).val());
      list = [number];
      out = [];
      while (item = list.shift()) {
        if (data[item]) {
          list.push.apply(list, data[item]);
        }
        if (data[item]) {
          out.push.apply(out, data[item]);
        }
      }
      out.sort(function(a, b) {
        return Number(a) - Number(b);
      });
      txt = '';
      for (_i = 0, _len = out.length; _i < _len; _i++) {
        t = out[_i];
        txt += "" + t + "\n";
      }
      txt = txt.slice(0, -1);
      ($('TEXTAREA#textarea')).text(txt);
      ($('textarea#textarea')).attr('rows', out.length);
      return void 0;
    });
    return void 0;
  });

}).call(this);
